Syslog
if83/production pull request #6
Opened 2018-04-05 23:31 UTC by oleksdiam

Now the rsyslog module is totally remastered. Sonar node has been remastered according to rsyslog module functionality. Nowadays rsyslog client needs to be inserted into profile code with this small frag:
  $log_application1     = {
    log_name => '/path/to/app/logs/*',
    log_tag  => 'app1_',     # also prefix of logname
    app_name => 'sonar', # also name of extra .conf file for rsyslog
    severity => 'info',
  }
  $log_application2     = {
    log_name => '/path/to/app/logs/*',
    log_tag  => 'app2_',
    app_name => 'app2',
    severity => 'info',
  }
  $apps   = [$log_application1, $log_application2]

  rsyslog::client { 'app' :
    user_apps    => $apps,
  }

2018-04-06 13:20 UTC, ipleten requested changes
Overall. I see that you got my idea.
But some changes are still needed.

2018-04-06 13:20 UTC, ipleten commented on modules/profile/manifests/rsyslog.pp
> +  base::ssh_user { $ssh_user:
Is it user common for all servers? If yes it should be moved to basenode.

2018-04-06 13:20 UTC, ipleten commented on modules/profile/manifests/rsyslog.pp
> +class profile::rsyslog {
profiles::rsyslog_server?

2018-04-06 13:20 UTC, ipleten commented on modules/profile/manifests/sonarqube.pp
> +  $log_sonar     = {
move that to  defined type below.

2018-04-06 13:20 UTC, ipleten commented on modules/rsyslog/manifests/client.pp
> +  $apps.each |$app| {
You don't need for-loop here.
One call of defined type should set up one application logging

2018-04-06 13:20 UTC, ipleten commented on modules/rsyslog/manifests/client.pp
> +  $apps = [ {log_name => '/var/log/secure', log_tag  => 'sys_', app_name => 'secure', severity => 'info'},
move that as a call to two defined types in profile::basenode

2018-04-06 13:20 UTC, ipleten commented on modules/rsyslog/manifests/client.pp
> +  $user_apps.each |$app| {
Why we have to similar thing here? user_apps and apps? what's the difference?

2018-04-06 13:32 UTC, bdeputat commented on modules/profile/manifests/rsyslog.pp
> +  base::ssh_user { $ssh_user:
That user will be in basenode

2018-04-06 13:42 UTC, oleksdiam commented on modules/rsyslog/manifests/client.pp
> +  $apps = [ {log_name => '/var/log/secure', log_tag  => 'sys_', app_name => 'secure', severity => 'info'},
ОК
просто ще один файл додасться :)

2018-04-06 13:42 UTC, oleksdiam commented on modules/rsyslog/manifests/client.pp
> +  $user_apps.each |$app| {
Це зникне, коли виконаю пункт вище. 
Треба було обробити 2 масиви

2018-04-06 13:42 UTC, oleksdiam commented on modules/rsyslog/manifests/client.pp
> +  $apps.each |$app| {
Так. Це я написав так для уніфікації коду.
Не у всіх по одному.

2018-04-06 13:42 UTC, oleksdiam commented on modules/profile/manifests/rsyslog.pp
> +class profile::rsyslog {
profile::rsyslog
Щоб не включати клас прямо в роль.
Або я не зрозумів питання

2018-04-06 13:43 UTC, oleksdiam commented on modules/profile/manifests/rsyslog.pp
> +  base::ssh_user { $ssh_user:
Це на випадок, коли юзери різні.
Хоча на цьому етапі збирались використовувати єдиного, але можливість залишили.
І це я включив виклик по чужому шаблону

2018-04-06 13:46 UTC, oleksdiam commented on modules/profile/manifests/sonarqube.pp
> +  $log_sonar     = {
так це і є вхідний хеш для  defined typе

2018-04-06 18:52 UTC, turnopil commented
Can you add a simple description how to use your rsyslog::config defined type?

2018-04-06 19:47 UTC, ipleten approved these changes
Except a few possible improvements it LGTM.

2018-04-06 19:47 UTC, ipleten commented on modules/rsyslog/templates/appslog.conf.erb
>      Facility="local7"
I'd also add "facility" as parameter in order to  have more control on logs on remote server but it's not necessary.

2018-04-06 19:47 UTC, ipleten commented on modules/profile/manifests/sonarqube.pp
> +    severity => 'info',
severity => 'info', is a default value in defined type so  it's not mandatory to put it in each deftype declaration.

2018-04-06 20:27 UTC, ipleten commented on modules/profile/manifests/rsyslog.pp
> +class profile::rsyslog {
I meant that name of class could be more meaningful.

2018-04-07 06:23 UTC, savroman approved these changes

2018-04-07 06:35 UTC, merged